import { describe, expect, test } from 'vitest'
import {
  advancePhase,
  cellAt,
  createInitialState,
  endPlayerTurn,
  getNpc,
  performBasicAction,
  runGlobalEnvironment,
  runThermalPhase,
} from './game'

describe('ProjectC v0 rules', () => {
  test('unused AP reserves at most one point for the next turn', () => {
    let state = createInitialState()
    state = performBasicAction(state, 'move', { x: 1, y: 7 })
    expect(state.ap).toBe(2)
    state = endPlayerTurn(state)
    while (state.phase !== 'player' && state.status === 'active') state = advancePhase(state)
    expect(state.ap).toBe(4)
  })

  test('Cell temperature influences Actor temperature during thermal phase', () => {
    const state = createInitialState()
    const npc = getNpc(state)
    const cell = cellAt(state, npc.position)!
    cell.groundTemp = 1
    const next = runThermalPhase(state)
    expect(getNpc(next).bodyTemperature).toBe(-2)
  })

  test('wind generated by sky temperature difference can move a cloud', () => {
    const state = createInitialState()
    for (const cell of state.cells) {
      cell.skyFill = 'clear'
      cell.cloudAge = 0
      cell.skyTemp = 2
      cell.groundTemp = 2
    }
    const source = cellAt(state, { x: 4, y: 2 })!
    const target = cellAt(state, { x: 5, y: 2 })!
    target.skyTemp = 0
    target.groundTemp = 0
    source.skyFill = 'cloud'
    const next = runGlobalEnvironment(state)
    expect(cellAt(next, { x: 5, y: 2 })?.skyFill).toBe('cloud')
    expect(cellAt(next, { x: 4, y: 2 })?.skyFill).toBe('clear')
  })
})
